import pandas as pd
import os

# Define the full dataset directly in the script
data = [
    {"message": "Hey everyone, how's the stream going?", "label": 0},
    {"message": "Does anyone know a good Minecraft server?", "label": 0},
    {"message": "This game is awesome! Loving it.", "label": 0},
    {"message": "Any tips for a beginner in Valorant?", "label": 0},
    {"message": "Don't forget to subscribe and like the stream.", "label": 0},
    {"message": "Thanks for the game! GG WP.", "label": 0},
    {"message": "Looking forward to tomorrow's tournament.", "label": 0},
    {"message": "This chat is so positive today!", "label": 0},
    {"message": "Follow me on Twitch for more gaming content.", "label": 0},
    {"message": "\"Loved your last video, very informative!\"", "label": 0},
    {"message": "Can someone recommend a good headset?", "label": 0},
    {"message": "What's the best strategy for this boss?", "label": 0},
    {"message": "Just joined, what did I miss?", "label": 0},
    {"message": "Hope everyone is having a great day!", "label": 0},
    {"message": "Anyone want to play after this?", "label": 0},
    {"message": "That was a sick play!", "label": 0},
    {"message": "Good vibes only in here.", "label": 0},
    {"message": "Where are you streaming from?", "label": 0},
    {"message": "I'm learning a lot from this stream.", "label": 0},
    {"message": "Keep up the great work!", "label": 0},
    {"message": "What kind of music do you listen to?", "label": 0},
    {"message": "Who else is hyped for the new update?", "label": 0},
    {"message": "Does anyone play [Game Name]?", "label": 0},
    {"message": "Just dropping in to say hi!", "label": 0},
    {"message": "This community is the best.", "label": 0},
    {"message": "What's your favorite character?", "label": 0},
    {"message": "So much fun watching you play!", "label": 0},
    {"message": "Wishing you all the best!", "label": 0},
    {"message": "Enjoying the chill stream.", "label": 0},
    {"message": "Time flies when you're having fun!", "label": 0},
    {"message": "What's the score?", "label": 0},
    {"message": "Did you see that goal?", "label": 0},
    {"message": "Laughing so hard right now!", "label": 0},
    {"message": "That's hilarious!", "label": 0},
    {"message": "What timezone are you in?", "label": 0},
    {"message": "Good morning everyone!", "label": 0},
    {"message": "How long have you been streaming?", "label": 0},
    {"message": "Any plans for the weekend?", "label": 0},
    {"message": "Just finished work, chilling out.", "label": 0},
    {"message": "What a great community here!", "label": 0},
    {"message": "Anyone else playing this tonight?", "label": 0},
    {"message": "Feeling good today!", "label": 0},
    {"message": "What's the weather like there?", "label": 0},
    {"message": "This is my favorite part of the game.", "label": 0},
    {"message": "You're so skilled at this!", "label": 0},
    {"message": "Keep up the amazing work!", "label": 0},
    {"message": "So inspiring to watch.", "label": 0},
    {"message": "What game are you playing next?", "label": 0},
    {"message": "Thanks for the advice!", "label": 0},
    {"message": "Just chilling and watching.", "label": 0},
    {"message": "Having a great time.", "label": 0},
    {"message": "What's your setup like?", "label": 0},
    {"message": "This chat is awesome!", "label": 0},
    {"message": "Sending good vibes!", "label": 0},
    {"message": "What's your Discord name?", "label": 0},
    {"message": "Can't wait for the next stream!", "label": 0},
    {"message": "You inspire me to play more.", "label": 0},
    {"message": "Such a chill atmosphere.", "label": 0},
    {"message": "GGs everyone, well played!", "label": 0},
    {"message": "Streamlabs: @AJ won the duel vs @Lalitkumar Solapure and won 10000 points FeelsGoodMan", "label": 0},
    {"message": "Streamlabs: @Lalitkumar Solapure, @AJ wants to duel you for 10000 points. You can !accept or !deny within 2 minutes.", "label": 0},
    {"message": "AJ: !duel @Lalitkumar Solapure all", "label": 0},
    {"message": "Streamlabs: @Mayank Adane won 200000000 MAAL and now has 56671723069 MAAL", "label": 0},
    {"message": "Streamlabs: @Aindrila Biswas won 200600 MAAL and now has 200600 MAAL", "label": 0},
    {"message": "Streamlabs: @, @Lalitkumar Solapure wants to duel you. You can !accept or !deny within 2 minutes.", "label": 0},
    {"message": "Streamlabs: @Laxman Prajapati lost 111261 MAAL and now has 0 MAAL", "label": 0},
    {"message": "AJ: !duel @Lalitkumar Solapure all", "label": 0},
    {"message": "Jay Desai: yr frnd is happy now on stream 🙂", "label": 0},
    {"message": "Streamlabs: @Ansh jadon lost 222342 MAAL and now has 0 MAAL", "label": 0},
    {"message": "Streamlabs: Lalitkumar Solapure gave 50000 MAAL to Ada.", "label": 0},
    {"message": "Streamlabs: @Forous lost 100000 MAAL and now has 21241 MAAL", "label": 0},
    {"message": "Streamlabs: @Sanidhya won 2000 MAAL and now has 11680 MAAL", "label": 0},
    {"message": "Join my server for free Nitro: discord.gg/fr33n1tr0", "label": 1},
    {"message": "Click here to claim your free Bitcoin: http://free-crypto.xyz", "label": 1},
    {"message": "Your PayPal account has been limited. Verify now: http://paypal-security.com", "label": 1},
    {"message": "Urgent: Your bank account is locked. Visit http://secure-bank.com to unlock.", "label": 1},
    {"message": "You've won a new iPhone! Claim it here: http://winner-rewards.info", "label": 1},
    {"message": "We detected unusual activity. Login fast: http://accounts-login.ru", "label": 1},
    {"message": "Get your government grant at http://fake-gov-grant.com", "label": 1},
    {"message": "Congratulations! You've won a $1000 Walmart gift card. Click here to claim: http://walmart-giveaway.co", "label": 1},
    {"message": "Reset your Facebook password: http://facebook-reset.xyz", "label": 1},
    {"message": "Update your Apple ID info here: http://apple-id-secure.com", "label": 1},
    {"message": "You've received a secure document: http://malicious-doc.biz", "label": 1},
    {"message": "Verify your Steam account for exclusive skins: http://steam-verify.com", "label": 1},
    {"message": "Free Robux! Go to bit.ly/robl0x-scam-now", "label": 1},
    {"message": "Your Netflix account has been suspended. Login to fix it: http://netflix-help.com", "label": 1},
    {"message": "Important: Your Amazon account needs attention. Click here: http://amazon-warning.net", "label": 1},
    {"message": "Claim your prize from last night's giveaway: http://stream-prizes.live", "label": 1},
    {"message": "Exclusive NFT drop! Connect your wallet at opensea-free.org", "label": 1},
    {"message": "Join my private Discord for cheats: discord.gg/cheat-codes", "label": 1},
    {"message": "Your credit card information is outdated. Update now: http://card-update.xyz", "label": 1},
    {"message": "Google has detected suspicious activity. Verify: http://google-security-check.com", "label": 1},
    {"message": "Limited time offer: Double your crypto! Send to this address: 0xDEADBEEF...", "label": 1},
    {"message": "You are eligible for unemployment benefits. Apply now: http://unemployment-grants.io", "label": 1},
    {"message": "Your phone number has been linked to a security breach. Click here: http://security-alert.cc", "label": 1},
    {"message": "Final warning! Your email will be suspended: http://email-verify.us", "label": 1},
    {"message": "We noticed unusual login attempts on your social media. Fix it: http://social-media-fix.online", "label": 1},
    {"message": "Discord Nitro giveaway! Enter here: free.nitro-discord.com", "label": 1},
    {"message": "Your Twitch Prime is expiring. Renew now: twitch-prime-renewal.net", "label": 1},
    {"message": "Claim your free skin for CS:GO here: csgoskins.ru", "label": 1},
    {"message": "Official announcement: Claim your airdrop at ethereum-airdrop.co", "label": 1},
    {"message": "Hey [Name], I need your help. Can you click this link: evil-link.com", "label": 1},
    {"message": "Your bank account requires immediate verification. Visit: fakebank.net/verify", "label": 1},
    {"message": "Congratulations, you've been selected for a special bonus! Click: bit.ly/bonus-claim", "label": 1},
    {"message": "Due to suspicious activity, your account has been temporarily locked. Restore access: secure-login.info/restore", "label": 1},
    {"message": "Exclusive offer: Get 1000 free V-Bucks! Visit: vbucks-generator.xyz", "label": 1},
    {"message": "Your cryptocurrency wallet needs to be re-verified. Use this link: mywallet-security.org", "label": 1},
    {"message": "Click to receive your free gift from us: gift-reward.co", "label": 1},
    {"message": "We detected a payment issue on your subscription. Update here: update-payment.cc", "label": 1},
    {"message": "Earn 500% interest on your crypto. Invest now: cryptoinvest.top/earn", "label": 1},
    {"message": "Your login attempt from a new device was blocked. Review activity: account-alert.info", "label": 1},
    {"message": "You have a pending delivery! Track it here: fake-delivery.biz", "label": 1},
    {"message": "Important tax refund notification. Claim your refund: tax-refund.online", "label": 1},
    {"message": "Your password has expired. Create a new one: password-reset.ru", "label": 1},
    {"message": "Free followers and likes for your social media! Get them now: socialboost.xyz", "label": 1},
    {"message": "Win a PlayStation 5! Enter competition: ps5-giveaway.site", "label": 1},
    {"message": "We found malware on your device. Scan now: security-scan.info", "label": 1},
    {"message": "Get a free VPN subscription: freevpn.tk", "label": 1},
    {"message": "Unlock exclusive content! Subscribe now: exclusive-content.club", "label": 1},
    {"message": "Your profile needs an urgent update to avoid deletion: profile-update.info", "label": 1},
    {"message": "Join our Telegram group for secret tips: t.me/cryptoleak", "label": 1}
]# This closing bracket ']' is absolutely essential!

# Get the script's directory
script_dir = os.path.dirname(os.path.abspath(__file__))
output_csv_path = os.path.join(script_dir, "phishing_dataset.csv")

# This line will now correctly report the number of items if the list is complete
print(f"DEBUG: Number of items in 'data' list: {len(data)}")

# Create a DataFrame
df_new = pd.DataFrame(data)

# Save to CSV (this will overwrite any existing file)
df_new.to_csv(output_csv_path, index=False)

print(f"✅ Successfully created/overwrote phishing_dataset.csv at: {output_csv_path}")
print(f"File size of created CSV: {os.path.getsize(output_csv_path)} bytes")
print("You can now run 'python train_model.py'")